sitemap:
  changefreq: weekly
module:
  mounts:
    - source: assets
      target: assets
    - source: layouts
      target: layouts
  imports:
    - path: github.com/gzu-ai/hugo-blox-builder/modules/blox-core
